<a href="https://colab.research.google.com/github/amirsakib16/PyTorch-Hands-on-Implementation-from-Scratch/blob/main/PyTorch_for_Deep_Learning_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INSTALL PYTORCH AND ENVIRONMENT SETUP**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

2.4.1+cu121


# **CREATING A TENSOR**

In [ ]:
array = [12,3,57,24,15]
Tensor = torch.tensor(array)
Tensor

tensor([12,  3, 57, 24, 15])

In [ ]:
emptyTensor = torch.empty(4,6)
emptyTensor

tensor([[6.8797e+11, 7.4412e+28, 1.6931e+22, 1.8179e+31, 7.7778e+31, 1.8891e+31],
        [7.1538e+22, 3.3744e-15, 3.2327e+27, 1.4582e-19, 3.3787e-15, 1.2931e+28],
        [8.3399e-30, 1.1998e-41, 5.9191e-40, 1.0394e+12, 2.5353e+30, 1.6956e-43],
        [5.0024e-41, 1.4184e-39, 1.8643e-31, 2.5353e+30, 1.6816e-43, 4.7512e-41]])

In [ ]:
zeroTensor = torch.zeros(4,3)
zeroTensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
oneTensor = torch.ones(4,7)
oneTensor

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
customizedTensor = torch.arange(5,27,3)
customizedTensor

tensor([ 5,  8, 11, 14, 17, 20, 23, 26])

In [ ]:
linspaceTensor = torch.linspace(7,8,12)
linspaceTensor

tensor([7.0000, 7.0909, 7.1818, 7.2727, 7.3636, 7.4545, 7.5455, 7.6364, 7.7273,
        7.8182, 7.9091, 8.0000])

In [ ]:
randomTensor = torch.rand(3,6)
randomTensor

tensor([[0.3542, 0.0953, 0.2372, 0.5053, 0.9843, 0.0398],
        [0.7787, 0.0909, 0.6284, 0.9739, 0.4008, 0.0884],
        [0.0553, 0.5427, 0.6587, 0.0435, 0.9180, 0.4601]])

In [ ]:
randomTensor = torch.randn(3,6)
randomTensor

tensor([[-0.8281, -0.3161, -1.0513,  1.2385,  0.9116,  0.5469],
        [-2.0492,  0.2865, -0.3462,  0.8323, -0.4620, -0.8598],
        [ 0.5482, -1.6489, -0.8659,  0.4895, -0.6139, -0.6056]])

In [ ]:
eyeTensor = torch.eye(5,5)
eyeTensor

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# **SHAPE MANIPULATION**

In [ ]:
Tensor = torch.tensor([12,45,67,87,65,43,123,45,78])
print(f"Original Tensor: {Tensor}")
viewTensor = Tensor.view(3,3)
print(f"View Tensor: \n{viewTensor}")


Original Tensor: tensor([ 12,  45,  67,  87,  65,  43, 123,  45,  78])
View Tensor: 
tensor([[ 12,  45,  67],
        [ 87,  65,  43],
        [123,  45,  78]])


In [ ]:
Tensor = torch.tensor([12,45,67,87,65,43,123,45,78,45,67,89])
print(f"Original Tensor: {Tensor}")
reshapeTensor = Tensor.reshape(3,4)
print(f"Reshape Tensor: \n{reshapeTensor}")


Original Tensor: tensor([ 12,  45,  67,  87,  65,  43, 123,  45,  78,  45,  67,  89])
Reshape Tensor: 
tensor([[ 12,  45,  67,  87],
        [ 65,  43, 123,  45],
        [ 78,  45,  67,  89]])


In [ ]:
tensor1 = torch.tensor([[12,6,78,90,65],[34,567,89,564,234]])
print(f"Original Tensor: \n{tensor1}")
transposeTensor = tensor1.transpose(0,1)
print(f"Transpose Tensor: \n{transposeTensor}")

tensor2 = tensor = torch.rand(2, 3, 4)
print(f"Original Tensor: \n{tensor2}")
transposeTensor = tensor2.transpose(0,2)
print(f"Transpose Tensor: \n{transposeTensor}")

Original Tensor: 
tensor([[ 12,   6,  78,  90,  65],
        [ 34, 567,  89, 564, 234]])
Transpose Tensor: 
tensor([[ 12,  34],
        [  6, 567],
        [ 78,  89],
        [ 90, 564],
        [ 65, 234]])
Original Tensor: 
tensor([[[0.5633, 0.5980, 0.7484, 0.6085],
         [0.4477, 0.8032, 0.3939, 0.1220],
         [0.7192, 0.6042, 0.9041, 0.9217]],

        [[0.2046, 0.7206, 0.2418, 0.1205],
         [0.0459, 0.2732, 0.2616, 0.1408],
         [0.2162, 0.5963, 0.4826, 0.7164]]])
Transpose Tensor: 
tensor([[[0.5633, 0.2046],
         [0.4477, 0.0459],
         [0.7192, 0.2162]],

        [[0.5980, 0.7206],
         [0.8032, 0.2732],
         [0.6042, 0.5963]],

        [[0.7484, 0.2418],
         [0.3939, 0.2616],
         [0.9041, 0.4826]],

        [[0.6085, 0.1205],
         [0.1220, 0.1408],
         [0.9217, 0.7164]]])


In [ ]:
tensor = torch.rand(2,4,3)
print(f"Original Tensor: \n{tensor}")
permuteTensor = tensor.permute(2,0,1) # <-- size(3,2,4)
print(f"Permuted Tensor: \n{permuteTensor}")

Original Tensor: 
tensor([[[0.2508, 0.7338, 0.2956],
         [0.2046, 0.8379, 0.5472],
         [0.0781, 0.8982, 0.5673],
         [0.6420, 0.7658, 0.3108]],

        [[0.1199, 0.9134, 0.5238],
         [0.1461, 0.8356, 0.4248],
         [0.3581, 0.9988, 0.5104],
         [0.5970, 0.8937, 0.3358]]])
Permuted Tensor: 
tensor([[[0.2508, 0.2046, 0.0781, 0.6420],
         [0.1199, 0.1461, 0.3581, 0.5970]],

        [[0.7338, 0.8379, 0.8982, 0.7658],
         [0.9134, 0.8356, 0.9988, 0.8937]],

        [[0.2956, 0.5472, 0.5673, 0.3108],
         [0.5238, 0.4248, 0.5104, 0.3358]]])


In [ ]:
tensor = torch.rand(2,4)
print(f"Shape of the tensor is : {tensor.shape}")
unsqueezeTensor = tensor.unsqueeze(0)
print(f"Shape of the tensor is : {unsqueezeTensor.shape}")
unsqueezeTensor = tensor.unsqueeze(1)
print(f"Shape of the tensor is : {unsqueezeTensor.shape}")
squeezeTensor = tensor.squeeze(0)
print(f"Shape of the tensor is : {squeezeTensor.shape}")

Shape of the tensor is : torch.Size([2, 4])
Shape of the tensor is : torch.Size([1, 2, 4])
Shape of the tensor is : torch.Size([2, 1, 4])
Shape of the tensor is : torch.Size([2, 4])


# **TENSOR OPERATION**

In [ ]:
tensor1 = torch.tensor([12,45,67,89])
tensor2 = torch.tensor([34,78,56,34])

tensor([ 46, 123, 123, 123])

In [ ]:
torch.add(tensor1, tensor2)

tensor([ 46, 123, 123, 123])

In [ ]:
torch.mul(tensor1, tensor2)

tensor([ 408, 3510, 3752, 3026])

In [ ]:
torch.div(tensor1, tensor2)

tensor([0.3529, 0.5769, 1.1964, 2.6176])

In [ ]:
tensor1 = torch.tensor([[2,4,6,8],
                       [2,9,5,3]])
tensor2 = torch.tensor([[1,7,],
                        [6,9],
                        [5,9],
                         [6,12]])
torch.matmul(tensor1, tensor2)

tensor([[104, 200],
        [ 99, 176]])

In [ ]:
torch.mm(tensor1, tensor2)

tensor([[104, 200],
        [ 99, 176]])

In [ ]:
batch1 = torch.tensor([[[1, 2],
                        [3, 4]],

                       [[5, 6],
                        [7, 8]]])

batch2 = torch.tensor([[[9, 10],
                        [11, 12]],

                       [[13, 14],
                        [15, 16]]])

result = torch.bmm(batch1, batch2)

print("Batch Matrix 1:")
print(batch1)

print("Batch Matrix 2:")
print(batch2)

print("Result of Batch Matrix Multiplication:")
print(result)


Batch Matrix 1:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Batch Matrix 2:
tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])
Result of Batch Matrix Multiplication:
tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])


In [ ]:
tensor1 = torch.tensor([[[1,2,3,4],
                        [5,6,7,8],
                        [9,10,11,12]],

                        [[13,14,15,16],
                        [17,18,19,20],
                        [21,22,23,24]]])
tensor2 = torch.tensor([[[9,8,7,6],
                        [5,4,3,2],
                        [4,5,6,7]],

                        [[9,1,3,6],
                        [17,18,19,20],
                        [6,9,2,4]]])
result1 = torch.cat((tensor1, tensor2), dim=1)
result2 = torch.cat((tensor1, tensor2), dim=2)
print(f"Tensor1: \n{tensor1}")
print()
print(f"Tensor2: \n{tensor2}")
print()
print(f"For dimension 1: \n{result1}")
print()
print(f"For dimension 2: \n{result2}")

Tensor1: 
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

Tensor2: 
tensor([[[ 9,  8,  7,  6],
         [ 5,  4,  3,  2],
         [ 4,  5,  6,  7]],

        [[ 9,  1,  3,  6],
         [17, 18, 19, 20],
         [ 6,  9,  2,  4]]])

For dimension 1: 
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [ 9,  8,  7,  6],
         [ 5,  4,  3,  2],
         [ 4,  5,  6,  7]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24],
         [ 9,  1,  3,  6],
         [17, 18, 19, 20],
         [ 6,  9,  2,  4]]])

For dimension 2: 
tensor([[[ 1,  2,  3,  4,  9,  8,  7,  6],
         [ 5,  6,  7,  8,  5,  4,  3,  2],
         [ 9, 10, 11, 12,  4,  5,  6,  7]],

        [[13, 14, 15, 16,  9,  1,  3,  6],
         [17, 18, 19, 20, 17, 18, 19, 20],
         [21, 22, 23, 24,  6,  9,  2,  4]]])


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
result = torch.stack((tensor1, tensor2), dim=0)

print("Stacked Tensor (dim=0):")
print(result)
print("Shape:", result.shape)


tensor1 = torch.tensor([[1, 2],
                        [3, 4]])

tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

result = torch.stack((tensor1, tensor2), dim=0)

print("Stacked Tensor (dim=0):")
print(result)
print("Shape:", result.shape)


Stacked Tensor (dim=0):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Stacked Tensor (dim=0):
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


# **INDEXING AND SPLITTING**


In [ ]:
import torch
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

index02 = torch.tensor([0, 2])
index21 = torch.tensor([2,1])

resultA = torch.index_select(tensor, dim=0, index=index02)
resultB = torch.index_select(tensor, dim=0, index=index21)
resultC = torch.index_select(tensor, dim=1, index=index02)
resultD = torch.index_select(tensor, dim=1, index=index21)

print("Selected Rows:")
print(f"Selected dimension row for 0 and 2: \n{resultA}")
print(f"Selected dimension row for 2 and 1: \n{resultB}")
print(f"Selected dimension column for 0 and 2: \n{resultC}")
print(f"Selected dimension column for 2 and 1: \n{resultD}")

tensor_3d = torch.tensor([[[1, 2], [3, 4]],
                          [[5, 6], [7, 8]],
                          [[9, 10], [11, 12]]])

index = torch.tensor([0, 2])
result = torch.index_select(tensor_3d, dim=0, index=index)

print("Selected Elements from 3D Tensor:")
print(result)


Selected Rows:
Selected dimension row for 0 and 2: 
tensor([[1, 2, 3],
        [7, 8, 9]])
Selected dimension row for 2 and 1: 
tensor([[7, 8, 9],
        [4, 5, 6]])
Selected dimension column for 0 and 2: 
tensor([[1, 3],
        [4, 6],
        [7, 9]])
Selected dimension column for 2 and 1: 
tensor([[3, 2],
        [6, 5],
        [9, 8]])
Selected Elements from 3D Tensor:
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 9, 10],
         [11, 12]]])


In [ ]:
tensor = torch.tensor([[10, 20, 30],
                       [40, 50, 60],
                       [70, 80, 90]])

index = torch.tensor([[0, 2, 1],
                      [1, 0, 2],
                      [2, 1, 0]])

resultX = torch.gather(tensor, dim=0, index=index)
resultY = torch.gather(tensor, dim=1, index=index)
print("Gathered Tensor for dimension 0:")
print(resultX)
print("Gathered Tensor for dimension 1:")
print(resultY)

tensor_3d = torch.tensor([[[10, 20], [30, 40]],
                          [[50, 60], [70, 80]]])

index = torch.tensor([[[0, 1], [1, 0]],
                      [[1, 0], [0, 1]]])

result = torch.gather(tensor_3d, dim=2, index=index)

print("Gathered 3D Tensor:")
print(result)


Gathered Tensor for dimension 0:
tensor([[10, 80, 60],
        [40, 20, 90],
        [70, 50, 30]])
Gathered Tensor for dimension 1:
tensor([[10, 30, 20],
        [50, 40, 60],
        [90, 80, 70]])
Gathered 3D Tensor:
tensor([[[10, 20],
         [40, 30]],

        [[60, 50],
         [70, 80]]])


In [ ]:
tensor = torch.zeros(3, 3, dtype=torch.int64)

index = torch.tensor([[0, 2, 1],
                      [0, 1, 2],
                      [1, 0, 2]])

src = torch.tensor([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])

tensor.scatter_(dim=1, index=index, src=src)

print("Modified Tensor after scatter_:")
print(tensor)


Modified Tensor after scatter_:
tensor([[10, 30, 20],
        [40, 50, 60],
        [80, 70, 90]])


In [ ]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])

splittedQ = torch.split(tensor, 2)
print("Splitted by 2")
for i in splittedQ:
    print(i)

tensor = torch.tensor([10, 20, 30, 40, 50])

splittedR = torch.split(tensor, [1, 3, 1])
print("Splitted by 1-3-1")
for j in splittedR:
    print(j)


Splitted by 2
tensor([1, 2])
tensor([3, 4])
tensor([5, 6])
Splitted by 1-3-1
tensor([10])
tensor([20, 30, 40])
tensor([50])


In [ ]:
tensorA = torch.tensor([12,45,67,89])
tensorB = torch.tensor([32,67,54,34])
tensorC = torch.tensor([12,45,76,89])

X = torch.eq(tensorA, tensorB)
print(X)
Y = torch.eq(tensorA, tensorC)
print(Y)

tensor([False, False, False, False])
tensor([ True,  True, False,  True])


In [ ]:
X = torch.ne(tensorA, tensorB)
print(X)
Y = torch.ne(tensorA, tensorC)
print(Y)

tensor([True, True, True, True])
tensor([False, False,  True, False])


In [ ]:
X = torch.gt(tensorA, tensorB)
print(X)
Y = torch.gt(tensorA, tensorC)
print(Y)

tensor([False, False,  True,  True])
tensor([False, False, False, False])


In [ ]:
X = torch.lt(tensorA, tensorB)
print(X)
Y = torch.lt(tensorA, tensorC)
print(Y)

tensor([ True,  True, False, False])
tensor([False, False,  True, False])


In [ ]:
import torch
import torch.nn as nn

linear_layer = nn.Linear(in_features=3, out_features=2)

input_tensor = torch.tensor([[1.0, 2.0, 3.0]])

output_tensor = linear_layer(input_tensor)

print("Input Tensor:", input_tensor)
print("Output Tensor:", output_tensor)


Input Tensor: tensor([[1., 2., 3.]])
Output Tensor: tensor([[0.1024, 1.1822]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn


conv_layer = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=3)
input_tensor = torch.randn(1, 3, 32, 32)
output = conv_layer(input_tensor)

print(f"Output shape: {output.shape}")

Output shape: torch.Size([1, 6, 30, 30])


In [ ]:
import torch
import torch.nn as nn


max_pool = nn.MaxPool2d(kernel_size=2)

input_tensor = torch.tensor([[[[1, 2, 3, 4],
                               [5, 6, 7, 8],
                               [9, 10, 11, 12],
                               [13, 14, 15, 16]]]])

output = max_pool(input_tensor)

print("Input Tensor:")
print(input_tensor)
print("Output Tensor:")
print(output)


Input Tensor:
tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16]]]])
Output Tensor:
tensor([[[[ 6,  8],
          [14, 16]]]])


In [ ]:
import torch
import torch.nn as nn

batch_norm = nn.BatchNorm2d(num_features=64)

input_tensor = torch.randn(1, 64, 32, 32)

output = batch_norm(input_tensor)

print("Input Tensor Shape:", input_tensor.shape)
print("Output Tensor Shape:", output.shape)


Input Tensor Shape: torch.Size([1, 64, 32, 32])
Output Tensor Shape: torch.Size([1, 64, 32, 32])


In [ ]:
import torch
import torch.nn as nn


relu = nn.ReLU()


input_tensor = torch.tensor([[-1.0, 2.0, -0.5],
                             [3.0, -4.0, 0.0]])

output = relu(input_tensor)

print("Input Tensor:\n", input_tensor)
print("Output Tensor after ReLU:\n", output)


Input Tensor:
 tensor([[-1.0000,  2.0000, -0.5000],
        [ 3.0000, -4.0000,  0.0000]])
Output Tensor after ReLU:
 tensor([[0., 2., 0.],
        [3., 0., 0.]])


In [ ]:
import torch
import torch.nn as nn


sigmoid = nn.Sigmoid()

input_tensor = torch.tensor([[-1.0, 2.0, 0.0],
                             [3.0, -4.0, 0.5]])

output = sigmoid(input_tensor)

print("Input Tensor:\n", input_tensor)
print("Output Tensor after Sigmoid:\n", output)


Input Tensor:
 tensor([[-1.0000,  2.0000,  0.0000],
        [ 3.0000, -4.0000,  0.5000]])
Output Tensor after Sigmoid:
 tensor([[0.2689, 0.8808, 0.5000],
        [0.9526, 0.0180, 0.6225]])


In [ ]:
import torch
import torch.nn as nn

tanh = nn.Tanh()


input_tensor = torch.tensor([[-1.0, 2.0, 0.0],
                             [3.0, -4.0, 0.5]])

output = tanh(input_tensor)

print("Input Tensor:\n", input_tensor)
print("Output Tensor after Tanh:\n", output)


Input Tensor:
 tensor([[-1.0000,  2.0000,  0.0000],
        [ 3.0000, -4.0000,  0.5000]])
Output Tensor after Tanh:
 tensor([[-0.7616,  0.9640,  0.0000],
        [ 0.9951, -0.9993,  0.4621]])


In [ ]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(4, 5),
    nn.ReLU(),
    nn.Linear(5, 3)
)

input_tensor = torch.tensor([[1.0, 2.0, 3.0, 4.0],
                             [4.0, 3.0, 2.0, 1.0]])


output = model(input_tensor)

print("Model architecture:\n", model)
print("\nInput:\n", input_tensor)
print("\nOutput:\n", output)


Model architecture:
 Sequential(
  (0): Linear(in_features=4, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=3, bias=True)
)

Input:
 tensor([[1., 2., 3., 4.],
        [4., 3., 2., 1.]])

Output:
 tensor([[ 0.1133, -0.5857,  1.3444],
        [ 0.1295, -0.4480,  0.9652]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch
import torch.nn as nn


logits = torch.tensor([[2.0, 1.0, 0.1]])
target = torch.tensor([0])


criterion = nn.CrossEntropyLoss()

loss = criterion(logits, target)

print("Cross-Entropy Loss:", loss.item())


Cross-Entropy Loss: 0.4170299470424652


In [ ]:
import torch
import torch.nn as nn


y_pred = torch.tensor([2.5, 0.0, 2.1, 1.6])
y_true = torch.tensor([3.0, -0.5, 2.0, 1.0])


criterion = nn.MSELoss()

loss = criterion(y_pred, y_true)

print("Mean Squared Error Loss:", loss.item())


Mean Squared Error Loss: 0.2175000011920929


In [ ]:
import torch
import torch.nn as nn


y_pred = torch.tensor([0.9, 0.2, 0.8, 0.1])
y_true = torch.tensor([1.0, 0.0, 1.0, 0.0])


criterion = nn.BCELoss()


loss = criterion(y_pred, y_true)

print("Binary Cross Entropy Loss:", loss.item())


Binary Cross Entropy Loss: 0.16425204277038574


# **GPU OPERATIONS**

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

if torch.cuda.is_available():
    tensor_gpu = torch.randn(3, 4, device='cuda')
    print(tensor_gpu.device)

    tensor_cpu = torch.randn(3, 4)
    tensor_moved = tensor_cpu.to(device)
    print(tensor_moved.device)

    tensor_back = tensor_moved.cpu()
    print(tensor_back.device)
else:
    print("CUDA not available, using CPU")

# **AUTOGRAD**

In [ ]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
y = x ** 2
z = y.sum()
z.backward()
print(x.grad)

x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1
y.backward()
print(f"dy/dx at x=3: {x.grad}")

x = torch.randn(3, requires_grad=True)
y = x * 2
z = y.mean()
z.backward()
print(x.grad)

with torch.no_grad():
    y = x * 2
    print(y.requires_grad)

y_detached = y.detach()
print(y_detached.requires_grad)

# **LINEAR REGRESSION IN NEURAL NETWORK**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)
X = torch.randn(100, 1)
y = 3 * X + 2 + torch.randn(100, 1) * 0.1

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

model = LinearRegressionModel()

criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

epochs = 100
for epoch in range(epochs):
    predictions = model(X)
    loss = criterion(predictions, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

print(f"Learned weight: {model.linear.weight.item():.4f}")
print(f"Learned bias: {model.linear.bias.item():.4f}")

# **MULTI-LAYER PERCEPTRON IN NEURAL NETWORK**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, hidden_size)
        self.fc3 = nn.Linear(hidden_size, output_size)
        self.relu = nn.ReLU()
    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = self.fc3(x)
        return x

model = MLP(input_size=10, hidden_size=64, output_size=2)
print(model)

dummy_input = torch.randn(32, 10)
output = model(dummy_input)
print(f"Output shape: {output.shape}")

# **BINARY CLASSIFICATION IN NEURAL NETWORK**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train).unsqueeze(1)
X_test = torch.FloatTensor(X_test)
y_test = torch.FloatTensor(y_test).unsqueeze(1)

class BinaryClassifier(nn.Module):
    def __init__(self, input_size):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.fc2 = nn.Linear(64, 32)
        self.fc3 = nn.Linear(32, 1)
        self.dropout = nn.Dropout(0.2)
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = F.relu(self.fc2(x))
        x = self.dropout(x)
        x = torch.sigmoid(self.fc3(x))
        return x

model = BinaryClassifier(input_size=20)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 100
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        model.eval()
        with torch.no_grad():
            test_outputs = model(X_test)
            test_loss = criterion(test_outputs, y_test)
            predictions = (test_outputs > 0.5).float()
            accuracy = (predictions == y_test).float().mean()
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Test Loss: {test_loss.item():.4f}, Accuracy: {accuracy.item():.4f}')

# **MULTI CLASS CLASSIFICATION IN NEURAL NETWORK**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=20, n_classes=5,
                          n_informative=15, n_redundant=5, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = torch.FloatTensor(X_train)
y_train = torch.LongTensor(y_train)
X_test = torch.FloatTensor(X_test)
y_test = torch.LongTensor(y_test)

class MultiClassClassifier(nn.Module):
    def __init__(self, input_size, num_classes):
        super(MultiClassClassifier, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.bn1 = nn.BatchNorm1d(128)
        self.fc2 = nn.Linear(128, 64)
        self.bn2 = nn.BatchNorm1d(64)
        self.fc3 = nn.Linear(64, num_classes)
        self.dropout = nn.Dropout(0.3)
    def forward(self, x):
        x = F.relu(self.bn1(self.fc1(x)))
        x = self.dropout(x)
        x = F.relu(self.bn2(self.fc2(x)))
        x = self.dropout(x)
        x = self.fc3(x)
        return x

model = MultiClassClassifier(input_size=20, num_classes=5)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 100
for epoch in range(epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        model.eval()
        with torch.no_grad():
            test_outputs = model(X_test)
            test_loss = criterion(test_outputs, y_test)
            _, predicted = torch.max(test_outputs, 1)
            accuracy = (predicted == y_test).float().mean()
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}, Test Accuracy: {accuracy.item():.4f}')